name: delete-older-releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
    - name: 删除旧的Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 30
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
